### ISSUE TITLE
Queue not supported

### ISSUE THREAD

**Issue by simonfranz** [Snowfire/Beautymail#23]
Hi there,

It does seem that beatymail cannot be queues
therefore this method should be implemented in Beautymail.php

	public function queue($view, array $data = [], $callback) {
		$data = array_merge($this->settings, $data);

		$this->mailer->queue($view, $data, $callback);
	}

Could you do this for the next version?
Thanks for the great package.

Best regards
Simon

**Comment by emilsundberg** [comment]
Thanks @simonfranz, it would be great if you could submit your code as a PR.

**Comment by simonfranz** [comment]
Done, I would be happy if this would be in the next version of beautymail.

**Comment by emilsundberg** [comment]
Thanks! I'll have a test look soon, then I'll merge and create a new release.

**Comment by emilsundberg** [comment]
Your updates are included  in 1.0.9 :smiley:

**Comment by ladaposamuel** [comment]
How can I use this,
Thank you?
I still get the error

`Only mailables may be queued.`
